Update PoW Difficulty
koinos/koinos-system-contracts pull request #19
Opened 2021-07-06 23:51 UTC by mvandeberg

Closes #18

2021-07-07 19:57 UTC, theoreticalbts requested changes

2021-07-07 19:57 UTC, theoreticalbts commented on contracts/pow/pow.cpp
> +}
Let's remove these commented-out lines.

2021-07-07 19:57 UTC, theoreticalbts commented on contracts/pow/pow.cpp
> +
This TODO comment needs a corresponding issue.

2021-07-07 19:57 UTC, theoreticalbts commented on contracts/pow/pow.cpp
> +   uint64_t effective_us = uint64_t( 1000 ) * TARGET_BLOCK_INTERVAL_MS;
This computation should be `initial_hashes_per_second = (1000 * initial_hashes_per_block) / TARGET_BLOCK_INTERVAL_MS;` so it Does the Right Thing even if `TARGET_BLOCK_INTERVAL_MS` is not evenly divisible by 1000.

However, if we do this, we also need an overflow check to be sure the multiplication in the numerator doesn't overflow.  Which can go in the same overflow analysis TODO issue as other overflow checks in this smart contract.

2021-07-07 19:57 UTC, theoreticalbts commented on contracts/pow/pow.cpp
> +
This `using difficulty_metadata` should be eliminated, and replace `difficulty_metadata` with `difficulty_metadata_v2` in the following code.  The `using` makes the code a little harder to follow than simply being explicit everywhere.

2021-07-07 19:57 UTC, theoreticalbts commented on contracts/pow/pow.cpp
> +   uint128_t dt_ms_prod = uint128_t(dt_ms) * DR_BONUS;
Again a TODO comment that needs an issue

2021-07-07 19:57 UTC, theoreticalbts commented on contracts/pow/pow.cpp
> +   // TODO:  Overflow analysis of these computations
Another TODO comment that needs an issue number

2021-07-07 19:57 UTC, theoreticalbts commented on contracts/pow/pow.cpp
> -
Why is it safe to delete this check?

2021-07-07 20:02 UTC, theoreticalbts commented
I filed issue #20 for the overflow TODO's, just reference the issue in the TODO comments.

2021-07-12 16:22 UTC, sgerbino commented
Usurped by #23.

2021-07-12 16:22 UTC, closed without merging